version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/housework-contract
permissions:
  - object: /home/ec2-user/
    pattern: '**'
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: before_deploy.sh
      runas: ec2-user
  AfterInstall:
    - location: after_deploy.sh
      runas: ec2-user
